const ANNUAL_INFLATION_RATE = 0.03

const ANNUAL_INCOME_GROWTH = 0.05
const ANNUAL_ASSETS_GROWTH_RATE = 0.07
const ANNUAL_SAFE_WITHDRAWAL_RATE = ANNUAL_ASSETS_GROWTH_RATE - ANNUAL_INFLATION_RATE

export default {
  ANNUAL_INCOME_GROWTH,
  ANNUAL_ASSETS_GROWTH_RATE,
  ANNUAL_EXPENSES_GROWTH_RATE: ANNUAL_INFLATION_RATE,
  ANNUAL_SAFE_WITHDRAWAL_RATE
}
